#!/usr/bin/env python3

"""Generate a zeptoforth flash-dictionary source from the audited core-1 BIN."""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


REFERENCE_SIZE = 19_120
REFERENCE_SHA256 = (
    "637f9b88b15b344a2147203eaa373d571"
    "224c6ff1eaa4e56d215fa9d780f50cf"
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="core1_pio_usb.bin")
    parser.add_argument("output", type=Path, help="generated Forth source")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    payload = args.input.read_bytes()
    digest = hashlib.sha256(payload).hexdigest()
    if len(payload) != REFERENCE_SIZE:
        raise SystemExit(
            f"unexpected payload size: {len(payload)} (expected {REFERENCE_SIZE})"
        )
    if digest != REFERENCE_SHA256:
        raise SystemExit(
            f"unexpected payload SHA-256: {digest} "
            f"(expected {REFERENCE_SHA256})"
        )
    if len(payload) % 4:
        raise SystemExit("payload size must be a multiple of four bytes")

    words = struct.unpack(f"<{len(payload) // 4}I", payload)
    lines = [
        "\\ Generated by generate_core1_payload.py; do not edit.",
        f"\\ Source: {args.input.name}",
        f"\\ Size: {len(payload)} bytes",
        f"\\ SHA-256: {digest}",
        "",
        "compile-to-flash",
        "cell align,",
        "create pio-usb-core1-v4-embedded-image",
    ]
    for offset in range(0, len(words), 4):
        chunk = words[offset : offset + 4]
        lines.append("  " + " ".join(f"${word:08X} ," for word in chunk))
    lines.extend(
        [
            f"{len(payload)} constant pio-usb-core1-v4-embedded-size",
            "cell align,",
            "create pio-usb-core1-v4-expected-sha256",
        ]
    )
    digest_bytes = bytes.fromhex(digest)
    for offset in range(0, len(digest_bytes), 8):
        chunk = digest_bytes[offset : offset + 8]
        lines.append("  " + " ".join(f"${byte:02X} c," for byte in chunk))
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"generated {args.output}")
    print(f"size={len(payload)} sha256={digest}")


if __name__ == "__main__":
    main()
